
import csv
import numpy as np
import pandas as pd

def load_position_motive_csv(file_path):
    """
    Loads a CSV file generated by Motive that includes position data for rigid bodies and returns
    a pandas DataFrame with the last row of the header used as column labels.

    Parameters:
    file_path (str): The path to the CSV file to be loaded.

    Returns:
    pandas.DataFrame: A DataFrame containing the parsed position and rotation data with appropriate column labels.
    """
    data = []
    column_labels = []
    with open(file_path, 'r', newline='') as csvfile:
        csv_reader = csv.reader(csvfile)
        
        # Skip the header information until we reach the line that starts with "Frame"
        for row in csv_reader:
            if row and 'Frame' in row[0]:
                column_labels = row  # This row is assumed to be the column labels
                break
        
        # Now read the actual data
        for row in csv_reader:
            if row and row[0].isdigit():  # Ensure this is a data row
                data.append([float(x) if i > 0 else int(x) for i, x in enumerate(row)])
    
    # Convert the data list to a NumPy array for easier manipulation later
    data_array = np.array(data)

    column_labels = ['Frame', 'Time', 'Theta', 'Phi', 'Rho', 'X', 'Y', 'Z'];

    # Convert the NumPy array to a DataFrame
    df = pd.DataFrame(data_array, columns=column_labels)
    
    return df
